### ISSUE TITLE
Unsupported scheme "node" for module "node:crypto"

### ISSUE THREAD

**Issue by CompuRoot** [JLCarveth/zippy#13]
Reproducing:

```
deno run -A --unstable paste.ts
```

result:
```
error: Unsupported scheme "node" for module "node:crypto". Supported schemes: [
    "data",
    "blob",
    "file",
    "http",
    "https",
]
    at file:///./auth.ts:14:41
```

**Comment by JLCarveth** [comment]
What version of Deno are you using?

**Comment by CompuRoot** [comment]
> What version of Deno are you using?

It was happened on 1.28. Updated `deno` to 1.37 and it started. 
`deno` moving fast, I see an year old binary changed a lot

Thank you !
